---
sidebar: sidebar
permalink: generate-report-upgrade-health-checker.html
keywords: upgrade, health, checker
summary: ""
---
= Generate upgrade plan with Upgrade Health Checker
:hardbreaks:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use Upgrade Health Checker to generate an update plan for a single or multiple ONTAP clusters.

.Steps

. Set the execute permission on the binary before running it the first time:
+
[source,cli]
----
chmod +x uhc
----
+
NOTE: Upgrade Health Checker is a self-contained package and will need to unpack itself before executing. This can take a few seconds.

. Before completing a full run of Upgrade Health Checker, perform a comprehensive check to verify available disk space and connectivity to the cluster and telemetry endpoint via HTTPS:
+
[source,cli]
----
./uhc --test all
----

. (Optional) If you would like to use a configuration file to store parameters, rename the sample `config.yaml.example` file located in the same location you downloaded the binary to `config.yaml`.
+
Here is a example config.yaml file:
+
----
# Application Configuration
APP:
  RUNS_PATH: "/opt/uhc/runs"

# Cluster Credentials
CLUSTER:
  IP: "x.x.x.x"
  USERNAME: "admin"
  PASSWORD: "xyz"
  TARGET_ONTAP_VERSION: ""  # Optional: Specify target ONTAP version (e.g., "9.16.1" or "current" to keep existing version). Leave empty to prompt user.
  ACCEPT_EULA: false  # Optional: Set to true to accept EULA via config. If false/empty, user will be prompted interactively.
----


. Run Upgrade Health Checker by entering the target ONTAP version, accepting the EULA, and running any additional parameters as needed.

.. Familiarize yourself with the available Upgrade Health Checker commands and parameters by running the help command:
+
[source,cli]
----
./uhc --help
----

.. (Optional) Specify a custom configuration file path and run path to streamline your workflow.

** To specify a custom config.yaml file path, use the following parameter:
+
[source,cli]
----
--config-path /path/to/config.yaml
----
+
If you do not specify a custom config.yaml file path, the default path will be './config.yaml'.

** To specify a custom runs path, use the following parameter:
+
[source,cli]
----
--runs-path /path/to/output/<cluster-name>/
----
+
It is recommended to create a custom output directory for each cluster.
+
You can also specify the runs path in the config.yaml file. If you do not specify a runs path, the default path will be './runs/<cluster-name>/'. The priority for specifying a runs path is as follows: CLI parameter > config.yaml > default path.

+
Alternatively, you can run Upgrade Health Checker with automatically with a script. Here is an example of a cronjob that runs the tool Monday through Friday at 4AM.
+
In this example the binary and config.yaml have been installed into /opt/uhc/tool/.
+
Bash script:
----
#!/bin/bash
cd /opt/uhc/tool
/opt/uhc/tool/uhc --accept-eula true --cluster-ip cluster-mgmt1.example.com --target-ontap-version current --cluster-username uhctool --cluster-password passw0rd
/opt/uhc/tool/uhc --accept-eula true --cluster-ip cluster-mgmt2.example.com --target-ontap-version 9.14.1 --cluster-username uhctool --cluster-password passw0rd
----
+
Cron job:
----
0 4 * * 1-5 /usr/local/bin/uhccron.sh
----
+
.Another example Script
--

[source,cli]
----
./uhc \
  --cluster-ip=<cluster-ip> \
  --cluster-username=<cluster-username> \
  --cluster-password=<cluster-password> \
  --target-ontap-version=<target-ontap-version> \
  --accept-eula=true
----
+
NOTE: The EULA is a multi-page document. Enter "all" to see the entire document at once and enter "y" to accept it.
+
After the ASUP is downloaded for a cluster, processing generally takes 1–2 minutes depending on the number of cluster nodes. Each Upgrade Health Checker run depends on the current load of the cluster and the current ONTAP version, because different ONTAP software versions handle AutoSupport collection differently.


. After Upgrade Health Checker completes it checks, navigate to the `runs` folder to view the upgrade plan and cluster report.
+
NOTE: Each execution of the program is a "unique run" and will have all the associated data, logs and results in the associated `runs` folder.

.. Open the `{cluster-name}_{YYYYMMDDHHMMSS}.html` report file in a web browser to view the report. If you are running it on a remote host, please download the `{cluster-name}_{YYYYMMDDHHMMSS}.html` report file first to a machine where you can view the report on a web browser.
+
The log path and report path are as follows:

** Log Path: `{output-path}/{unique-run-dir}/{cluster-name}/logs`
** Report Path: `{output-path}/{unique-run-dir}/{cluster-name}/results/{cluster-name}_{YYYYMMDDHHMMSS}.html`

.. 