settings:
  name: "Upgrade Health Checker"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true

sidebar: 
  entries:
  - title: Upgrade Health Checker docs
    url: "/index.html"
  - title: Release notes
    entries:
    - title: What's new
      url: "/whats-new.html"
  - title: Get started
    entries:
    - title: Learn about Upgrade Health Checker
      url: "/learn-about-upgrade-health-checker.html"
    - title: Set up Upgrade Health Checker
      url: "/set-up-upgrade-health-checker.html"
  - title: Use Upgrade Health Checker
    entries:
    - title: Generate an ONTAP upgrade report
      url: "/generate-report-upgrade-health-checker.html"
    - title: Automate report generation
      url: "/automate-report-upgrade-health-checker.html"
  - title: Reference
    entries:
    - title: Input Parameters Guide
      url: "/upgrade-health-checker-input-parameters-guide.html"
  - title: FAQ
    url: "/faq-upgrade-health-checker.html"
  - title: Legal notices
    url: "/legal-notices.html"