---
sidebar: sidebar
permalink: set-up-upgrade-health-checker.html
keywords: upgrade, health, checker
summary: ""
---
= Download and set up Upgrade Health Checker
:hardbreaks:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can download Upgrade Health Checker to generate onsite, comprehensive checks before upgrading to a newer version of ONTAP.

.Before you begin

When preparing to set up the Upgrade Health Checker virtual machine, it is recommended to acquire a virtual machine with the following specifications:

* Processing and memory: m5.large VM or equivalent with 2 vCPUs and 8 GiB RAM.
* Operating system: Ubuntu 22.04 for optimal compatibility.
* Storage: Provide a root volume with a minimum of 100GB and an additional NFS volume of at least 100GB to ensure data preservation if the VM is compromised.
* Hosting requirements: Place the VM in a location with cluster connectivity and internet access to allow for automatic tool updates. If internet access is unavailable, consult NetApp for guidance.
* Recommended packages: Install a Web Server to facilitate access.


.Steps

. Download the Upgrade Health Checker binary from the link:https://mysupport.netapp.com/site/tools/tool-eula/upgrade-health-checker[NetApp Support Site^].

. Set up the Upgrade Health Checker virtual machine and use SSH to place the binary in the location of your choice.

. Configure a service account and role for cluster access. For cluster access via Upgrade Health Checker, it is recommended to create the service role as a REST-role. 
+
You must create the service account for the http application. Use the following CLI commands to configure the necessary permissions:
+
[source,cli]
----
security login rest-role create -role uhctool -api /api -access readonly -vserver
----
+
[source,cli]
----
security login rest-role create -role uhctool -api /api/support/autosupport -access read_create_modify -vserver
----
+
[source,cli]
----
security login rest-role create -role uhctool -api /api/support/autosupport/messages -access read_create_modify -vserver
----
+
[source,cli]
----
vserver services web access create -name spi -role uhctool -vserver
----
+
NOTE: This final command is essential for granting SPI access, enabling ASUP downloads to the VM.
+
[source,cli]
----
security login create -user-or-group-name uhctool -role uhctool -application http -authentication-method password
----
+
[source,cli]
----
security login create -user-or-group-name uhctool -role uhctool -application ssh -authentication-method password
----
+
NOTE: It is recommended to build an Ansible playbook to automate the deployment of the role and user to all clusters.

. Set up credential management to secure access to the application. If you have CyberArk and Conjour, you can configure your environment to avoid passing credentials through a yaml file or command line.
.. Create required CyberArk Safes:
... Create a Safe (Main-Conjur-Safe) that holds the application credentials and secrets
... Create a Safe (API-Credentials-Safe) that holds the Conjur Host ID and API Key
... Create a Safe (Conjur-SSL-Certificate) that holds the necessary certificate

.. Create the configuration (Conjur.conf) and identity (Conjur.identity) files for this application:
... Conjur.conf
+
----
account:
plugins:[]
appliance_url: https://FQDN
cert_file: /etc/conjur.pem
----
... Conjur.identity
+
----
machine https://FQDN/authn
login host /prodvault/devops/<Main-Conjur-Safe>/host1
password XXXXXX
----

+
Here is an example of how to use CyberArk and Conjour in an ansible playbook:
.. Install Conjur Ansible Collection, which includes the Conjur Ansible Lookup Plugin, on Ansible Host: 
+                           
----
ansible-galaxy collection install cyberark.conjur
----
.. Create a task in a yaml file to fetch the username and password from CyberArk:
+
----
conjur_username: "{{ lookup('cyberark.conjur.conjur_variable', 'prodvault/devops/<Main-Conjur-Safe>/<Account name>/username', validate_certs=false) }}"
conjur_password: "{{ lookup('cyberark.conjur.conjur_variable', 'prodvault/devops/<Main-Conjur-Safe>/<Account name>/password', validate_certs=false) }}"
----

