---
sidebar: sidebar
permalink: setup-email-upgrade-health-checker.html
keywords: upgrade, health, checker
summary: "You can set up emails to receive Upgrade Health Checker reports."
---
= Receive Upgrade Health Checker reports by email
:hardbreaks:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Upgrade Health Checker can email reports directly to your inbox. Enable this feature through the config.yaml file or a command line argument. When enabled, Upgrade Health Checker sends generated reports (HTML, Excel, or JSON) to one or more recipients via an SMTP server. When disabled, no reports are sent. If report generation fails and email is enabled, Upgrade Health Checker emails the log files to the configured recipients. 

== Configure using the config.yaml file
You can configure email settings in the config.yaml file by enabling email reports, adding SMTP server details, and specifying recipient addresses and report formats.

. Enable email reports in the config.yaml file.
+
----
# Email Report Configuration
EMAIL:
  ENABLED: true
----
. Add the SMTP configuration settings, sender details, and subject:
+
----
# SMTP Server Configuration
EMAIL:
  ENABLED: true
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [<port-number>]
----
. Add recipient email addresses and set which report formats the system sends by email, for example, HTML, EXCEL, JSON, or ALL. You can also use authentication and encryption:
+
----
# Recipient Email Addresses, report formats
EMAIL:
  ENABLED: true
  TO: <recipient>
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  RECIPIENTS: "user1@example.com, user2@example.com"
  REPORT_FORMATS: "HTML,EXCEL,JSON"   # valid values: HTML, EXCEL, JSON or ALL
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
    USE_SMTP_AUTH: true
    USE_TLS: true
    USE_SSL: true 
    USERNAME: "user@example.com"
    PASSWORD: "********"
----

== Configure using command line arguments
You can configure basic email settings using command line arguments to enable reports, specify recipients, and select report formats.

. Enable email reports using command line arguments:
+
----
./uhc --email-enabled=true
----
. Provide recipient email addresses: 
+
----
./uhc --email-recipients="user1@example.com, user2@example.com"
----
. Configure which report formats are sent by email, for example, HTML, EXCEL, JSON:
+
----
./uhc --email-report-formats=HTML,EXCEL,JSON
----

[NOTE]
================
You can configure the following three attributes using command line arguments or the config.yaml file. You can configure all remaining attributes only in the config.yaml file:

* Email Enabled

* Email Recipients

* Email Report Formats

Note that command line arguments override config.yaml file values.

For example:
----
./uhc \
  --email-enabled=true
  --email-recipients="user1@example.com, user2@example.com" \
  --email-report-formats=HTML,EXCEL,JSON \
----
----
EMAIL:
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
----
================


// OTHERDOC-233, 2026-JUN-04
// OTHERDOC-244, 2026-JUL-10