---
sidebar: sidebar
permalink: upgrade-health-checker-input-parameters.html
keywords: upgrade, health, checker, input, parameter
summary: "You can learn more about the input parameters for Upgrade Health Checker to assist you with generating an upgrade report for your ONTAP cluster."
---
= Learn about the input parameters for Upgrade Health Checker
:hardbreaks:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can learn more about the input parameters for Upgrade Health Checker and how to provide them through CLI arguments, configuration files, or interactive prompts to assist you with generating an upgrade report for your ONTAP cluster.

== Input methods priority

Upgrade Health Checker provides several input options for all parameters. Its priority order for accepting inputs is:

. CLI arguments (highest priority)
. Configuration file (`config.yaml`)
. Interactive prompts (lowest priority)

When a parameter is provided through multiple methods, the tool will use the value from the highest priority source.

== Input parameters

=== Cluster IP 

The `--cluster-ip` parameter specifies the IP address or hostname of the ONTAP cluster to connect to. 

The priority order for providing this parameter is:

. CLI argument: `--cluster-ip`
. Config file: `CLUSTER.IP`
. Interactive prompt

.Examples
[%collapsible]
====

* CLI argument:
+
`./uhc --cluster-ip 192.168.1.100`

* Config.yaml:
+
----
CLUSTER:
  IP: "192.168.1.100"
----

* Interactive mode (if not provided above):
+
Tool will prompt: `Enter cluster IP address:`

====

=== Cluster username

The `--cluster-username` parameter specifies the username for authenticating with the ONTAP cluster. 

The priority order for providing this parameter is:

. CLI argument: `--cluster-username`
. Config file: `CLUSTER.USERNAME`
. Interactive prompt

.Examples
[%collapsible]
====

* CLI argument:
+
`./uhc --cluster-username admin`

* Config.yaml:
+
----
CLUSTER:
  USERNAME: "admin"
----

* Interactive mode (if not provided above):
+
Tool will prompt: `Enter cluster username:`

====


=== Cluster password

The `--cluster-password` parameter specifies the password for authenticating with the ONTAP cluster. 

The priority order for providing this parameter is:

. CLI argument: `--cluster-password`
. Config file: `CLUSTER.PASSWORD`
. Interactive prompt (secure input)

.Examples
[%collapsible]
====

* CLI argument (not recommended for security):
+
`./uhc --cluster-password mypassword`

* Config.yaml (ensure file permissions are restricted):
+
----
CLUSTER:
  PASSWORD: "mypassword"
----

* Interactive mode (recommended - password hidden):
+
Tool will prompt: `Enter cluster password:`

====


=== Target ONTAP version

The `--target-ontap-version` parameter specifies the ONTAP version you want to upgrade to for analysis. Use "current" to keep the existing cluster ONTAP version.

The priority order for providing this parameter is:

. CLI argument: `--target-ontap-version`
. Config file: `CLUSTER.TARGET_ONTAP_VERSION`
. Interactive selection menu

.Examples
[%collapsible]
====

* CLI argument:
+
Updated version of ONTAP: `./uhc --target-ontap-version 9.15.1`
+
Keep current version of ONTAP: `./uhc --target-ontap-version current`

* Config.yaml:
+
----
CLUSTER:
  TARGET_ONTAP_VERSION: "9.15.1"
----

* Interactive mode (if not provided above):
+
Tool will display available versions and prompt for selection

====

=== Accept EULA

The `--accept-eula` parameter specifies whether to accept the End User License Agreement. Must be set to `true` to proceed.

The priority order for providing this parameter is:

. CLI argument: `--accept-eula`
. Config file: `CLUSTER.ACCEPT_EULA`
. Interactive prompt

.Examples
[%collapsible]
====

* CLI argument:
+
`./uhc --accept-eula true`

* Config.yaml:
+
----
CLUSTER:
  ACCEPT_EULA: true
----

* Interactive mode (if not provided above):
+
Tool will display EULA and prompt for acceptance

====


=== Configuration file path

The `--config-path` parameter specifies the path to a custom configuration YAML file.

The priority order for providing this parameter is:

. CLI argument: `--config-path`
. Default: `config.yaml`

.Examples
[%collapsible]
====

* CLI argument:
+
`./uhc --config-path /path/to/custom_config.yaml`

* Default (if not provided):
+
Tool will look for config.yaml in the current directory

====


=== Run output path

The `--runs-path` parameter specifies a custom directory for storing run outputs and reports.

The priority order for providing this parameter is:

. CLI argument: `--runs-path`
. Config file: `APP.RUNS_PATH`
. Default: `./runs`

.Examples
[%collapsible]
====

* CLI argument:
+
`./uhc --runs-path /custom/output/path`

* Config.yaml:
+
----
APP:
  RUNS_PATH: "/custom/output/path"
----

* Default (if not provided):
+
Tool will use `./runs` directory

====


=== Skip compatibility check

The `--skip-compatibility-check` parameter bypasses hardware compatibility checks and uses the specified version of ONTAP you want to upgrade to.

CAUTION: Only use this option if you are certain the target ONTAP version is compatible with your hardware.

The priority order for providing this parameter is:

. CLI argument: `--skip-compatibility-check`
. Config file: `CLUSTER.SKIP_COMPATIBILITY_CHECK`
. Default: `false`

.Examples
[%collapsible]
====

* CLI argument:
+
`./uhc --skip-compatibility-check true`

* Config.yaml:
+
----
CLUSTER:
  SKIP_COMPATIBILITY_CHECK: true
----
====

=== Disable telemetry

To disable telemetry, add the following to your `config.yaml` file:

----
TELEMETRY:
  ENABLED: false
----

=== Disable automatic updates

To disable automatic updates for Upgrade Health Checker, add the following to your `config.yaml` file:

----
AUTO_UPDATE:
  ENABLED: false
----

== Examples using each input method

=== Combined CLI arguments

----
./uhc \
  --cluster-ip 192.168.1.100 \
  --cluster-username admin \
  --cluster-password mypassword \
  --target-ontap-version 9.15.1 \
  --accept-eula true \
  --config-path /path/to/custom_config.yaml \
  --runs-path /custom/output \
  --skip-compatibility-check false
----

=== Config.yaml file

----
CLUSTER:
  IP: "192.168.1.100"
  USERNAME: "admin"
  PASSWORD: "mypassword"
  TARGET_ONTAP_VERSION: "9.15.1"
  ACCEPT_EULA: true
  SKIP_COMPATIBILITY_CHECK: false

APP:
  RUNS_PATH: "/custom/output"
----

=== Interactive mode

To prompt all required input parameters interactively, run Upgrade Health Checker without arguments:

[source,bash]
----
./uhc
----


== Additional commands

These commands provide some additional capabilities beyond the full run of the tool:

[source,bash]
----
# Display help
./uhc --help

# Display version
./uhc --version

# Test cluster connectivity
./uhc --test-connectivity cluster

# Test telemetry connectivity
./uhc --test-connectivity telemetry

# Test auto-update connectivity
./uhc --test-connectivity autoupdate

# Run all tests
./uhc --test all
----
